name: Update Scholarly Data (Deprecated)

# This workflow is deprecated.
# Please use update-research-data.yml instead.

on:
  # No triggers - this workflow will never run
  workflow_dispatch: # Only manual trigger is available

jobs:
  update-scholarly-data:
    runs-on: ubuntu-latest
    steps:
      - name: Notification
        run: echo "This workflow is deprecated. Please use update-research-data.yml instead."
