name: Update Scholarly Data

on:
  workflow_dispatch: # Manual trigger option
  schedule:
    - cron: ${{ vars.SCHOLARLY_CRON_SCHEDULE || '0 0 * * 0' }} # Default: Weekly on Sunday at midnight UTC

jobs:
  update-scholarly-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scholarly requests tqdm

      - name: Run scholarly data fetcher
        env:
          CROSSREF_MAILTO: ${{ secrets.CROSSREF_MAILTO }}
        run: |
          python utils/scholarly_data_fetcher.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add public/content/research.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update research data [skip ci]" && git push)
