name: Update Research Data

# To change the schedule frequency:
# 1. Go to Repository Settings > Secrets and Variables > Actions
# 2. Create or update a repository variable called SCHOLARLY_CRON_SCHEDULE
# 3. Use cron syntax: '0 0 * * 0' for weekly on Sunday
#    Other examples:
#    - Daily at midnight UTC: '0 0 * * *'
#    - Monthly on the 1st: '0 0 1 * *'
#    - Every 6 hours: '0 */6 * * *'
# Last updated: 2024-04-02

on:
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  update-research-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Check if requirements.txt exists, otherwise install specific packages
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install scholarly requests tqdm
          fi

      - name: Run data fetcher script
        env:
          CROSSREF_MAILTO: ${{ secrets.CROSSREF_MAILTO }}
        run: python utils/scholarly_data_fetcher.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/content/research.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update research data [skip ci]" && git push)
